/** Stable draw domain error codes for UI mapping. */

export const DrawErrorCode = {
  INVALID_INPUT: "DRAW_INVALID_INPUT",
  DUPLICATE_ENTRY: "DRAW_DUPLICATE_ENTRY",
  UNKNOWN_ENTRY: "DRAW_UNKNOWN_ENTRY",
  UNKNOWN_GROUP: "DRAW_UNKNOWN_GROUP",
  CAPACITY_EXCEEDED: "DRAW_CAPACITY_EXCEEDED",
  INSUFFICIENT_CAPACITY: "DRAW_INSUFFICIENT_CAPACITY",
  EMPTY_GROUPS: "DRAW_EMPTY_GROUPS",
  EMPTY_ENTRIES: "DRAW_EMPTY_ENTRIES",
  INVALID_SEED: "DRAW_INVALID_SEED",
  SEED_SLOT_CONFLICT: "DRAW_SEED_SLOT_CONFLICT",
} as const;

export type DrawErrorCode =
  (typeof DrawErrorCode)[keyof typeof DrawErrorCode];
