/** Stable match-rule domain error codes for UI mapping. */

export const MatchRuleErrorCode = {
  INVALID_BEST_OF_SETS: "MATCH_RULE_INVALID_BEST_OF_SETS",
  INVALID_POINTS_TO_WIN: "MATCH_RULE_INVALID_POINTS_TO_WIN",
  INVALID_WIN_BY: "MATCH_RULE_INVALID_WIN_BY",
  INVALID_MAX_POINTS: "MATCH_RULE_INVALID_MAX_POINTS",
  INCONSISTENT_DECIDING_SET: "MATCH_RULE_INCONSISTENT_DECIDING_SET",
  INVALID_CHANGE_ENDS_AT: "MATCH_RULE_INVALID_CHANGE_ENDS_AT",
  RULE_NOT_RESOLVABLE: "MATCH_RULE_NOT_RESOLVABLE",
  INVALID_RULE: "MATCH_RULE_INVALID",
} as const;

export type MatchRuleErrorCode =
  (typeof MatchRuleErrorCode)[keyof typeof MatchRuleErrorCode];
