/** Stable scoring domain error codes for UI mapping. */

export const ScoringErrorCode = {
  NEGATIVE_SCORE: "SCORING_NEGATIVE_SCORE",
  NON_INTEGER_SCORE: "SCORING_NON_INTEGER_SCORE",
  TIE_SCORE: "SCORING_TIE_SCORE",
  INVALID_SET_SCORE: "SCORING_INVALID_SET_SCORE",
  EXCEEDS_MAX_POINTS: "SCORING_EXCEEDS_MAX_POINTS",
  SET_NOT_COMPLETE: "SCORING_SET_NOT_COMPLETE",
  EXTRA_SETS: "SCORING_EXTRA_SETS",
  INVALID_SET_NUMBER: "SCORING_INVALID_SET_NUMBER",
  INVALID_ENTRY_IDS: "SCORING_INVALID_ENTRY_IDS",
  INVALID_RULE: "SCORING_INVALID_RULE",
  INVALID_INPUT: "SCORING_INVALID_INPUT",
} as const;

export type ScoringErrorCode =
  (typeof ScoringErrorCode)[keyof typeof ScoringErrorCode];
